server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # Microservicio de Monopatines
            - id: monopatin
              uri: http://localhost:8084
              predicates:
                - Path=/monopatin/**

            # Microservicio de Paradas
            - id: parada
              uri: http://localhost:8085
              predicates:
                - Path=/parada/**

            # Microservicio de Tarifas
            - id: tarifas
              uri: http://localhost:8086
              predicates:
                - Path=/tarifa/**

            # Microservicio de Viajes
            - id: viajes
              uri: http://localhost:8088
              predicates:
                - Path=/viaje/**

            # Microservicio de Cuentas (puerto 8087)
            - id: cuenta
              uri: http://localhost:8087
              predicates:
                - Path=/cuenta/**

            # Microservicio de Usuarios (puerto 8087)
            - id: usuario
              uri: http://localhost:8087
              predicates:
                - Path=/usuario/**

security:
  jwt:
    secret: j7ZookpUTYxclaULynjypGQVKMYXqOXMI+/1sQ2gOV1BF6VOHw6OzYj9RNZY4GcHAE3Igrah3MZ26oLrY/3y4Q==
    expiration-ms: 86400000 # 1 d√≠a

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[org.springframework.web]': DEBUG